import { useState } from 'react';
import { BadgeCheck, BriefcaseBusiness, Check, ClipboardCopy, Clock3, Eye, EyeOff, LockKeyhole, Printer, Settings2, ShieldCheck, Wrench } from 'lucide-react';
import { Link } from 'wouter';
import { useGetPassport, useGetProfile, useListCredentials, type Credential } from '@workspace/api-client-react';

type ShareSettings = { sharePhoto: boolean; shareHomeBase: boolean; shareSkills: boolean; shareCertifications: boolean };
type PassportCredential = { name: string; issuer: string; expires: string; state: 'current' | 'expiring' | 'profile' };
const LEGACY_SHARE_KEY = 'stagewire-share-settings-v14';
const PHOTO_KEY = 'stagewire-profile-photo-preview-v14';
function legacySettings(): ShareSettings | null { try { const raw = localStorage.getItem(LEGACY_SHARE_KEY); return raw ? { sharePhoto: false, shareHomeBase: false, shareSkills: true, shareCertifications: true, ...JSON.parse(raw) } : null; } catch { return null; } }
function dateOnly(value: string | null | undefined) { return value ? value.slice(0, 10) : ''; }
function daysUntil(date: string) { if (!date) return null; const target = new Date(`${date}T12:00:00`).getTime(); const today = new Date(); today.setHours(12,0,0,0); return Math.ceil((target - today.getTime()) / 86400000); }
function isShareableCredential(cert: Credential) { if (cert.status === 'planned') return false; const days = daysUntil(dateOnly(cert.expires)); return days === null || days >= 0; }
function expirationLabel(date: string) { if (!date) return ''; const value = new Date(`${date}T12:00:00`); return Number.isNaN(value.getTime()) ? date : new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(value); }
export default function CareerPassportV14Page() {
  const passport = useGetPassport(); const profile = useGetProfile(); const credentialQuery = useListCredentials(); const data = passport.data; const worker = profile.data; const photo = localStorage.getItem(PHOTO_KEY) || ''; const [copied, setCopied] = useState(false);
  if (passport.isLoading || profile.isLoading || credentialQuery.isLoading) return <div className="page-wrap"><div className="card card-pad"><h2>Building Career Passport…</h2></div></div>;
  if (passport.isError || profile.isError || credentialQuery.isError || !data || !worker) return <div className="page-wrap"><div className="error-box"><strong>Career Passport could not be opened.</strong><button className="btn btn-quiet" onClick={() => { passport.refetch(); profile.refetch(); credentialQuery.refetch(); }}>Try again</button></div></div>;
  const share: ShareSettings = legacySettings() ?? { sharePhoto: worker.sharePhoto, shareHomeBase: worker.shareHomeBase, shareSkills: worker.shareSkills, shareCertifications: worker.shareCertifications };
  const totalHours = data.experience.reduce((sum, item) => sum + item.hours, 0);
  const learned = (credentialQuery.data || []).filter(isShareableCredential);
  const learnedByName = new Map(learned.map((cert) => [cert.name.trim().toLowerCase(), cert]));
  const seenCredentialNames = new Set<string>();
  const credentials: PassportCredential[] = [...data.certifications, ...learned.map((cert) => cert.name)].filter((name) => { const key = name.trim().toLowerCase(); if (!key || seenCredentialNames.has(key)) return false; seenCredentialNames.add(key); return true; }).map((name) => { const match = learnedByName.get(name.trim().toLowerCase()); if (!match) return { name, issuer: '', expires: '', state: 'profile' as const }; const expires = dateOnly(match.expires); const days = daysUntil(expires); return { name: match.name, issuer: match.issuer.trim(), expires, state: days !== null && days <= 60 ? 'expiring' as const : 'current' as const }; });
  const visibleCerts = share.shareCertifications ? credentials : []; const visibleSkills = share.shareSkills ? data.skills : [];
  const approvedSummary = [
    `${data.workerName} — StageWire Career Passport`,
    `Primary role: ${data.primaryRole}`,
    data.additionalRoles.length ? `Additional roles: ${data.additionalRoles.join(', ')}` : '',
    share.shareHomeBase && worker?.homeCityState ? `Home base: ${worker.homeCityState}` : '',
    `Recorded calls: ${data.completedCallCount}`,
    `Recorded hours: ${totalHours.toFixed(1)}h`,
    data.experience.length ? `Experience: ${data.experience.map((item) => `${item.role} (${item.calls} calls / ${item.hours.toFixed(1)}h)`).join('; ')}` : '',
    visibleSkills.length ? `Skills: ${visibleSkills.join(', ')}` : '',
    visibleCerts.length ? `Credentials: ${visibleCerts.map((item) => `${item.name}${item.issuer ? ` — ${item.issuer}` : ''}${item.expires ? ` — expires ${expirationLabel(item.expires)}` : ''}`).join('; ')}` : '',
    'Worker-controlled summary generated from StageWire recorded work.',
  ].filter(Boolean).join('\n');
  const copyApprovedSummary = async () => { try { await navigator.clipboard.writeText(approvedSummary); setCopied(true); window.setTimeout(() => setCopied(false), 2500); } catch { const field = document.createElement('textarea'); field.value = approvedSummary; field.setAttribute('readonly', ''); field.style.position = 'fixed'; field.style.opacity = '0'; document.body.appendChild(field); field.select(); document.execCommand('copy'); field.remove(); setCopied(true); window.setTimeout(() => setCopied(false), 2500); } };
  return <div className="page-wrap"><div className="page-heading print-hide"><div><Link href="/vault-v14" className="link-text">The Vault</Link><div className="eyebrow" style={{ marginTop: 22 }}>Worker-controlled proof package</div><h1 style={{ marginTop: 10 }}>Career Passport</h1><p className="subtitle">Preview exactly what another person would see. Private information stays out.</p></div><div className="form-actions"><Link href="/worker-setup" className="btn btn-secondary"><Settings2 size={19} /> Sharing controls</Link><button className="btn btn-secondary" type="button" onClick={copyApprovedSummary}>{copied ? <><Check size={19}/> Copied</> : <><ClipboardCopy size={19}/> Copy approved summary</>}</button><button className="btn btn-primary" onClick={() => window.print()}><Printer size={19} /> Print / save PDF</button></div></div>
  <div className="card card-pad passport-privacy-summary print-hide"><div><div className="eyebrow">Share preview</div><h2 style={{ marginTop: 7 }}>You control this package.</h2><p className="subtitle">Phone, email, emergency contact, private uploaded files, Money, and Work/Life check-ins are never shown here or copied into the approved summary.</p></div><div className="privacy-chip-row"><span className={share.sharePhoto ? 'chip' : 'chip muted-chip'}>{share.sharePhoto ? <Eye size={15}/> : <EyeOff size={15}/>} Photo</span><span className={share.shareHomeBase ? 'chip' : 'chip muted-chip'}>{share.shareHomeBase ? <Eye size={15}/> : <EyeOff size={15}/>} Home base</span><span className={share.shareSkills ? 'chip' : 'chip muted-chip'}>{share.shareSkills ? <Eye size={15}/> : <EyeOff size={15}/>} Skills</span><span className={share.shareCertifications ? 'chip' : 'chip muted-chip'}>{share.shareCertifications ? <Eye size={15}/> : <EyeOff size={15}/>} Certifications</span></div></div>
  <article className="card card-pad receipt-paper"><header className="receipt-head"><div className="passport-identity">{share.sharePhoto && photo && <img className="passport-photo" src={photo} alt="Worker profile"/>}<div><div className="eyebrow">StageWire / Career Passport</div><h2 style={{ marginTop: 8 }}>{data.workerName}</h2><p className="subtitle" style={{ marginTop: 6 }}>{data.primaryRole}</p>{data.additionalRoles.length > 0 && <p className="call-meta" style={{ marginTop: 8 }}>{data.additionalRoles.join(' · ')}</p>}{share.shareHomeBase && worker?.homeCityState && <p className="call-meta" style={{ marginTop: 8 }}>{worker.homeCityState}</p>}</div></div><span className="badge badge-active"><LockKeyhole size={15}/> Worker approved</span></header>
  <div className="stats-grid" style={{ marginTop: 26 }}><div className="card stat-card"><span className="stat-label">Recorded calls</span><strong className="stat-value">{data.completedCallCount}</strong></div><div className="card stat-card"><span className="stat-label">Recorded hours</span><strong className="stat-value">{totalHours.toFixed(1)}h</strong></div><div className="card stat-card"><span className="stat-label">Roles worked</span><strong className="stat-value">{data.experience.length}</strong></div><div className="card stat-card"><span className="stat-label">Shared credentials</span><strong className="stat-value">{visibleCerts.length}</strong></div></div>
  <section style={{ marginTop: 28 }}><div className="eyebrow">Recorded experience</div><h2 style={{ marginTop: 8 }}>Work by role</h2>{data.experience.length ? <div className="experience-list" style={{ marginTop: 16 }}>{data.experience.map((item) => <div className="experience-row" key={item.role}><span><b>{item.role}</b><small>{item.calls} completed {item.calls === 1 ? 'call' : 'calls'}</small></span><span><Clock3 size={17} style={{ verticalAlign: '-3px' }}/> {item.hours.toFixed(1)}h</span></div>)}</div> : <p className="subtitle">Finished calls will build your experience record here.</p>}</section>
  <div className="passport-grid" style={{ marginTop: 28 }}>{share.shareSkills ? <section className="card card-pad"><div className="eyebrow">Skills</div><h2 style={{ marginTop: 8 }}><Wrench size={20} style={{ verticalAlign: '-3px' }}/> Capabilities</h2>{visibleSkills.length ? <div className="chip-row" style={{ marginTop: 16 }}>{visibleSkills.map((item) => <span className="chip" key={item}>{item}</span>)}</div> : <p className="subtitle">No skills saved yet.</p>}</section> : <HiddenSection label="Skills"/>}{share.shareCertifications ? <section className="card card-pad"><div className="eyebrow">Credentials</div><h2 style={{ marginTop: 8 }}><ShieldCheck size={20} style={{ verticalAlign: '-3px' }}/> Certifications</h2>{visibleCerts.length ? <div className="experience-list" style={{ marginTop: 16 }}>{visibleCerts.map((item) => <div className="experience-row" key={item.name}><span><b><BadgeCheck size={15} style={{ verticalAlign: '-2px' }}/> {item.name}</b><small>{item.issuer || 'Issuer not saved'}{item.expires ? ` · expires ${expirationLabel(item.expires)}` : ''}</small></span><span className={`badge ${item.state === 'current' ? 'badge-active' : 'badge-finished'}`}>{item.state === 'profile' ? 'shared' : item.state}</span></div>)}</div> : <p className="subtitle">No current certifications saved yet.</p>}<p className="help-text" style={{ marginTop: 14 }}>Current and expiring Learning credentials carry their saved issuer and expiration details into this preview. Expired and planned credentials stay private. Older profile-only certification names are labeled shared without claiming a current expiration status.</p></section> : <HiddenSection label="Certifications"/>}</div>
  <section className="card" style={{ padding: 20, marginTop: 28 }}><div className="eyebrow">Worker-owned proof</div><h2 style={{ marginTop: 8 }}><BriefcaseBusiness size={21} style={{ verticalAlign: '-3px' }}/> Built from finished calls and worker-approved credentials</h2><p className="subtitle" style={{ marginTop: 10 }}>StageWire builds this summary from the worker's recorded calls and shareable Learning credentials. It is not a public profile and nothing is shared automatically.</p></section>
  <footer className="receipt-foot" style={{ marginTop: 30 }}><span><LockKeyhole size={15} style={{ verticalAlign: '-3px' }}/> Worker controlled</span><span><BadgeCheck size={15} style={{ verticalAlign: '-3px' }}/> {data.completedCallCount} recorded calls</span><span>StageWire Career Passport</span></footer></article></div>;
}
function HiddenSection({ label }: { label: string }) { return <section className="card card-pad passport-hidden"><EyeOff size={22}/><div><div className="eyebrow">Not shared</div><h2 style={{ marginTop: 6 }}>{label}</h2><p className="subtitle">Hidden by the worker.</p></div></section>; }
