import { useMemo, useState } from 'react';
import { Check, HardHat, Plus, RotateCcw, Wrench } from 'lucide-react';
type Item={id:string;label:string};
const roleKits:Record<string,Item[]>={Stagehand:[{id:'gloves',label:'Work gloves'},{id:'boots',label:'Work boots'},{id:'knife',label:'Utility knife / multitool'},{id:'light',label:'Flashlight / headlamp'},{id:'water',label:'Water'},{id:'sharpie',label:'Sharpie'}],Rigger:[{id:'helmet',label:'Approved helmet'},{id:'harness',label:'Harness'},{id:'lanyard',label:'Approved positioning / fall gear'},{id:'gloves',label:'Work gloves'},{id:'boots',label:'Work boots'},{id:'light',label:'Headlamp'}],Pusher:[{id:'gloves',label:'Work gloves'},{id:'boots',label:'Work boots'},{id:'radio',label:'Radio if issued'},{id:'water',label:'Water'},{id:'sharpie',label:'Sharpie'}],Audio:[{id:'gloves',label:'Work gloves'},{id:'boots',label:'Work boots'},{id:'light',label:'Flashlight'},{id:'tester',label:'Cable tester if personally carried'},{id:'sharpie',label:'Sharpie'}],Lighting:[{id:'gloves',label:'Work gloves'},{id:'boots',label:'Work boots'},{id:'light',label:'Flashlight'},{id:'wrench',label:'Adjustable wrench'},{id:'sharpie',label:'Sharpie'}],Video:[{id:'gloves',label:'Work gloves'},{id:'boots',label:'Work boots'},{id:'light',label:'Flashlight'},{id:'sharpie',label:'Sharpie'}],Carpentry:[{id:'gloves',label:'Work gloves'},{id:'boots',label:'Work boots'},{id:'eye',label:'Eye protection'},{id:'measure',label:'Tape measure'},{id:'pencil',label:'Pencil / marker'}]};
const KEY='stagewire-crew-kit-v14';
function read():Record<string,boolean>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function startingRole(){const requested=new URLSearchParams(window.location.search).get('role')||'';const exact=Object.keys(roleKits).find(r=>r.toLowerCase()===requested.toLowerCase());return exact||'Stagehand'}
export default function CrewKitPage(){const [role,setRole]=useState(startingRole);const [checked,setChecked]=useState(read);const [custom,setCustom]=useState<Item[]>([]);const items=useMemo(()=>[...(roleKits[role]||[]),...custom],[role,custom]);const toggle=(id:string)=>{const key=`${role}:${id}`;const next={...checked,[key]:!checked[key]};setChecked(next);localStorage.setItem(KEY,JSON.stringify(next))};const reset=()=>{const next={...checked};items.forEach(i=>delete next[`${role}:${i.id}`]);setChecked(next);localStorage.setItem(KEY,JSON.stringify(next))};const add=()=>{const label=window.prompt('Add something you personally want on this checklist');if(label?.trim())setCustom(v=>[...v,{id:`custom-${Date.now()}`,label:label.trim()}])};const done=items.filter(i=>checked[`${role}:${i.id}`]).length;
return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Before the call</div><h1 style={{marginTop:10}}>Crew Kit</h1><p className="subtitle">A fast personal checklist based on the role you are walking into.</p></div><span className="badge badge-active"><HardHat size={16}/> {done}/{items.length} ready</span></div><section className="card card-pad"><div className="field" style={{maxWidth:360}}><label htmlFor="kit-role">Role for this call</label><select id="kit-role" value={role} onChange={e=>setRole(e.target.value)}>{Object.keys(roleKits).map(r=><option key={r}>{r}</option>)}</select></div><div className="experience-list" style={{marginTop:20}}>{items.map(item=>{const key=`${role}:${item.id}`;return <button type="button" className="experience-row" key={item.id} onClick={()=>toggle(item.id)} style={{width:'100%',textAlign:'left'}}><span><b>{item.label}</b><small>{checked[key]?'Packed / ready':'Tap when ready'}</small></span><span className={`badge ${checked[key]?'badge-active':'badge-finished'}`}>{checked[key]?<><Check size={15}/> Ready</>:'Not yet'}</span></button>})}</div><div className="form-actions" style={{marginTop:18}}><button className="btn btn-secondary" onClick={add}><Plus size={18}/> Add my item</button><button className="btn btn-quiet" onClick={reset}><RotateCcw size={17}/> Reset checklist</button></div></section><section className="card card-pad" style={{marginTop:22}}><div className="eyebrow">Important</div><h2 style={{marginTop:7}}><Wrench size={21}/> This is a memory aid, not a safety standard.</h2><p className="subtitle">The employer, venue, union, manufacturer, competent person, and the actual job conditions determine required PPE, tools, training, inspection and procedures. StageWire should never tell a worker that checking boxes makes a hazardous task safe.</p></section></div>}
