import { useState } from 'react';
import { BadgeCheck, BookOpenCheck, CalendarClock, GraduationCap, Plus, ShieldCheck, Wrench } from 'lucide-react';
type Cert = { id: number; name: string; issuer: string; expires: string; status: 'current' | 'expiring' | 'planned' };
const KEY = 'stagewire-learning-certs-v14';
const defaults: Cert[] = [{ id: 1, name: 'OSHA 10', issuer: '', expires: '', status: 'current' }];
function read(): Cert[] { try { const value = JSON.parse(localStorage.getItem(KEY) || 'null'); return Array.isArray(value) ? value : defaults; } catch { return defaults; } }
export default function LearningCenterPage() { const [certs, setCerts] = useState(read); const [showAdd, setShowAdd] = useState(false); const save = (next: Cert[]) => { setCerts(next); localStorage.setItem(KEY, JSON.stringify(next)); }; const add = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name') || '').trim(); if (!name) return; save([...certs, { id: Date.now(), name, issuer: String(form.get('issuer') || ''), expires: String(form.get('expires') || ''), status: 'planned' }]); setShowAdd(false); };
return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Skills / education / certifications</div><h1 style={{ marginTop: 10 }}>Learning</h1><p className="subtitle">Know what you have, what is coming due, and what you want to learn next.</p></div><button className="btn btn-primary" onClick={() => setShowAdd(true)}><Plus size={19}/> Add certification</button></div>
<div className="stats-grid"><div className="card stat-card"><span className="stat-label">Tracked</span><strong className="stat-value">{certs.length}</strong></div><div className="card stat-card"><span className="stat-label">Current</span><strong className="stat-value">{certs.filter(c=>c.status==='current').length}</strong></div><div className="card stat-card"><span className="stat-label">Planned</span><strong className="stat-value">{certs.filter(c=>c.status==='planned').length}</strong></div></div>
<section className="card card-pad" style={{marginTop:22}}><div className="eyebrow">Credential wallet</div><h2 style={{marginTop:7}}><BadgeCheck size={22}/> Your certifications</h2><div className="experience-list" style={{marginTop:16}}>{certs.map(cert=><div className="experience-row" key={cert.id}><span><b>{cert.name}</b><small>{cert.issuer || 'Issuer not added'}{cert.expires ? ` · expires ${cert.expires}` : ''}</small></span><span className={`badge badge-${cert.status==='current'?'active':'finished'}`}>{cert.status}</span></div>)}</div></section>
<div className="passport-grid" style={{marginTop:22}}><section className="card card-pad"><GraduationCap size={25}/><div className="eyebrow" style={{marginTop:12}}>Next skills</div><h2 style={{marginTop:7}}>Build the career, not just the next call.</h2><p className="subtitle">Use planned credentials as a personal roadmap. StageWire should eventually connect workers to real training without pretending every class or provider is equal.</p></section><section className="card card-pad"><CalendarClock size={25}/><div className="eyebrow" style={{marginTop:12}}>Expiration awareness</div><h2 style={{marginTop:7}}>No surprise expired cards.</h2><p className="subtitle">Expiration dates belong here once. Future reminders can warn the worker before a credential becomes a problem on a call.</p></section><section className="card card-pad"><Wrench size={25}/><div className="eyebrow" style={{marginTop:12}}>Role-based learning</div><h2 style={{marginTop:7}}>Learn what the job actually uses.</h2><p className="subtitle">Training should eventually map to roles like stagehand, rigger, pusher, audio, lighting, video and carpentry instead of dumping everyone into one giant course list.</p></section><section className="card card-pad"><ShieldCheck size={25}/><div className="eyebrow" style={{marginTop:12}}>Worker controlled</div><h2 style={{marginTop:7}}>Share proof, not your whole life.</h2><p className="subtitle">Credentials can feed Career Passport only when the worker chooses to include them.</p></section></div>
{showAdd&&<div className="modal-surface" role="dialog" aria-modal="true"><div className="modal-dialog card"><div className="card-pad"><div className="eyebrow">Credential</div><h2 style={{marginTop:7}}>Add certification</h2><form onSubmit={add}><div className="form-grid" style={{marginTop:18}}><div className="field"><label>Name *</label><input name="name" required placeholder="OSHA 30, Dante Level 1…"/></div><div className="field"><label>Issuer</label><input name="issuer" placeholder="Training provider"/></div><div className="field"><label>Expiration date</label><input name="expires" type="date"/></div></div><div className="form-actions"><button className="btn btn-primary" type="submit"><BookOpenCheck size={18}/> Save</button><button className="btn btn-quiet" type="button" onClick={()=>setShowAdd(false)}>Not now</button></div></form></div></div></div>}</div>; }
