import { useMemo, useState } from 'react';
import { BadgeCheck, BookOpenCheck, CalendarClock, GraduationCap, Plus, ShieldCheck, Trash2, Wrench } from 'lucide-react';
type Cert = { id: number; name: string; issuer: string; expires: string; status: 'current' | 'expiring' | 'planned' };
const KEY = 'stagewire-learning-certs-v14';
const defaults: Cert[] = [{ id: 1, name: 'OSHA 10', issuer: '', expires: '', status: 'current' }];
function read(): Cert[] { try { const value = JSON.parse(localStorage.getItem(KEY) || 'null'); return Array.isArray(value) ? value : defaults; } catch { return defaults; } }
function daysUntil(date: string) { if (!date) return null; const target = new Date(`${date}T12:00:00`).getTime(); const today = new Date(); today.setHours(12,0,0,0); return Math.ceil((target - today.getTime()) / 86400000); }
function effectiveStatus(cert: Cert): Cert['status'] { if (cert.status === 'planned') return 'planned'; const days = daysUntil(cert.expires); return days !== null && days <= 60 ? 'expiring' : 'current'; }
export default function LearningCenterPage() { const [certs, setCerts] = useState(read); const [showAdd, setShowAdd] = useState(false); const normalized = useMemo(() => certs.map(cert => ({ ...cert, status: effectiveStatus(cert) })), [certs]); const save = (next: Cert[]) => { setCerts(next); localStorage.setItem(KEY, JSON.stringify(next)); }; const add = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name') || '').trim(); if (!name) return; const status = String(form.get('status') || 'current') as Cert['status']; save([...certs, { id: Date.now(), name, issuer: String(form.get('issuer') || ''), expires: String(form.get('expires') || ''), status }]); setShowAdd(false); }; const changeStatus = (id:number, status:Cert['status']) => save(certs.map(c => c.id===id ? {...c,status} : c)); const remove = (id:number) => save(certs.filter(c=>c.id!==id));
return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Skills / education / certifications</div><h1 style={{ marginTop: 10 }}>Learning</h1><p className="subtitle">Know what you have, what is coming due, and what you want to learn next.</p></div><button className="btn btn-primary" onClick={() => setShowAdd(true)}><Plus size={19}/> Add certification</button></div>
<div className="stats-grid"><div className="card stat-card"><span className="stat-label">Tracked</span><strong className="stat-value">{normalized.length}</strong></div><div className="card stat-card"><span className="stat-label">Current</span><strong className="stat-value">{normalized.filter(c=>c.status==='current').length}</strong></div><div className="card stat-card"><span className="stat-label">Expiring ≤60 days</span><strong className="stat-value">{normalized.filter(c=>c.status==='expiring').length}</strong></div><div className="card stat-card"><span className="stat-label">Planned</span><strong className="stat-value">{normalized.filter(c=>c.status==='planned').length}</strong></div></div>
<section className="card card-pad" style={{marginTop:22}}><div className="eyebrow">Credential wallet</div><h2 style={{marginTop:7}}><BadgeCheck size={22}/> Your certifications</h2><p className="help-text">Mark something planned until you actually earn it. Current credentials can feed Career Passport; planned ones cannot.</p><div className="experience-list" style={{marginTop:16}}>{normalized.map(cert=>{const days=daysUntil(cert.expires); return <div className="experience-row" key={cert.id}><span><b>{cert.name}</b><small>{cert.issuer || 'Issuer not added'}{cert.expires ? ` · expires ${cert.expires}` : ' · no expiration saved'}{days!==null && days<0 ? ` · expired ${Math.abs(days)} days ago` : days!==null && days<=60 ? ` · ${days} days left` : ''}</small></span><span className="form-actions"><select aria-label={`${cert.name} status`} value={cert.status==='expiring'?'current':cert.status} onChange={e=>changeStatus(cert.id,e.target.value as Cert['status'])}><option value="current">Earned / current</option><option value="planned">Planned</option></select><span className={`badge badge-${cert.status==='current'?'active':'finished'}`}>{cert.status}</span><button className="icon-btn" aria-label={`Remove ${cert.name}`} onClick={()=>remove(cert.id)}><Trash2 size={17}/></button></span></div>})}</div></section>
<div className="passport-grid" style={{marginTop:22}}><section className="card card-pad"><GraduationCap size={25}/><div className="eyebrow" style={{marginTop:12}}>Next skills</div><h2 style={{marginTop:7}}>Build the career, not just the next call.</h2><p className="subtitle">Use planned credentials as a personal roadmap. Earning one is a deliberate status change—StageWire never assumes you passed a course.</p></section><section className="card card-pad"><CalendarClock size={25}/><div className="eyebrow" style={{marginTop:12}}>Expiration awareness</div><h2 style={{marginTop:7}}>No surprise expired cards.</h2><p className="subtitle">Earned credentials automatically show as expiring when they are within 60 days of the saved expiration date.</p></section><section className="card card-pad"><Wrench size={25}/><div className="eyebrow" style={{marginTop:12}}>Role-based learning</div><h2 style={{marginTop:7}}>Learn what the job actually uses.</h2><p className="subtitle">Training should map to stagehand, rigger, pusher, audio, lighting, video, carpentry and other real backstage roles—not one giant generic list.</p></section><section className="card card-pad"><ShieldCheck size={25}/><div className="eyebrow" style={{marginTop:12}}>Worker controlled</div><h2 style={{marginTop:7}}>Share proof, not your whole life.</h2><p className="subtitle">Current credentials can feed Career Passport only when certification sharing is enabled. Planned credentials stay private.</p></section></div>
{showAdd&&<div className="modal-surface" role="dialog" aria-modal="true"><div className="modal-dialog card"><div className="card-pad"><div className="eyebrow">Credential</div><h2 style={{marginTop:7}}>Add certification</h2><form onSubmit={add}><div className="form-grid" style={{marginTop:18}}><div className="field"><label>Name *</label><input name="name" required placeholder="OSHA 30, Dante Level 1…"/></div><div className="field"><label>Issuer</label><input name="issuer" placeholder="Training provider"/></div><div className="field"><label>Expiration date</label><input name="expires" type="date"/></div><div className="field"><label>Status</label><select name="status" defaultValue="current"><option value="current">I earned this</option><option value="planned">I plan to earn this</option></select></div></div><div className="form-actions"><button className="btn btn-primary" type="submit"><BookOpenCheck size={18}/> Save</button><button className="btn btn-quiet" type="button" onClick={()=>setShowAdd(false)}>Not now</button></div></form></div></div></div>}</div>; }
