import { Archive, Calculator, LockKeyhole, ReceiptText, ShieldCheck, WalletCards } from 'lucide-react';
import { Link } from 'wouter';
import { useGetVault } from '@workspace/api-client-react';
function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value || 0); }
export default function MoneyCenterPage() {
  const vault = useGetVault(); const data = vault.data;
  if (vault.isLoading) return <div className="page-wrap"><div className="card card-pad"><h2>Opening Money…</h2></div></div>;
  if (vault.isError || !data) return <div className="page-wrap"><div className="error-box"><strong>Money could not be opened.</strong><button className="btn btn-quiet" onClick={() => vault.refetch()}>Try again</button></div></div>;
  const gross = data.calls.reduce((sum, call) => sum + call.gross, 0); const hours = data.calls.reduce((sum, call) => sum + call.hours, 0); const reserve = gross * 0.25; const afterReserve = Math.max(0, gross - reserve);
  return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Worker money / planning</div><h1 style={{ marginTop: 10 }}>Money</h1><p className="subtitle">Finished calls build this automatically. No second timesheet inside StageWire.</p></div><span className="badge badge-finished"><LockKeyhole size={15} /> Private</span></div>
    <div className="stats-grid"><div className="card stat-card"><span className="stat-label">Finished calls</span><strong className="stat-value">{data.calls.length}</strong></div><div className="card stat-card"><span className="stat-label">Recorded hours</span><strong className="stat-value">{hours.toFixed(1)}h</strong></div><div className="card stat-card"><span className="stat-label">Recorded gross</span><strong className="stat-value">{money(gross)}</strong></div><div className="card stat-card"><span className="stat-label">25% reserve example</span><strong className="stat-value">{money(reserve)}</strong></div></div>
    <section className="card card-pad" style={{ marginTop: 22 }}><div className="eyebrow">Tax planning</div><h2 style={{ marginTop: 7 }}><Calculator size={22} /> Simple reserve view</h2><p className="subtitle">This is a planning aid, not tax advice and not a tax return. StageWire is showing a simple 25% reserve against recorded gross so a worker can see the money before spending it.</p><div className="receipt-grid" style={{ marginTop: 18 }}><div><div className="receipt-label">Recorded gross</div><div className="receipt-value">{money(gross)}</div></div><div><div className="receipt-label">Example reserve</div><div className="receipt-value">{money(reserve)}</div></div><div><div className="receipt-label">After example reserve</div><div className="receipt-value">{money(afterReserve)}</div></div></div></section>
    <section style={{ marginTop: 28 }}><div className="section-label"><h2>Call earnings</h2><span className="help-text">Every row comes from a finished Call Receipt.</span></div>{data.calls.length === 0 ? <div className="card empty"><WalletCards size={26} /><h3>No finished calls yet.</h3><p>Close a call and it will appear here automatically.</p></div> : <div className="calls-list">{data.calls.map((call) => <Link href={`/receipt/${call.id}`} className="card call-card" key={call.id}><div className="call-main"><span className="badge badge-finished">Finished</span><h3>{call.showName}</h3><p>{call.venue} · {call.role}</p></div><div className="call-money"><strong>{money(call.gross)}</strong><span>{call.hours.toFixed(1)}h</span><span className="link-text"><ReceiptText size={16} /> Receipt</span></div></Link>)}</div>}</section>
    <div className="card card-pad" style={{ marginTop: 24 }}><div className="eyebrow">One record</div><h2 style={{ marginTop: 7 }}>Nothing to enter again.</h2><p className="subtitle">Correct the Call Receipt if a work record is wrong. The Vault, Career Passport, and Money views should all read from that same worker-owned record.</p><div className="form-actions" style={{ marginTop: 16 }}><Link href="/vault-v14" className="btn btn-secondary"><Archive size={19} /> The Vault</Link></div><div className="privacy-rule"><ShieldCheck size={18} /> Money information is private and is never part of Career Passport sharing.</div></div>
  </div>;
}
