import { useState } from 'react';
import { HeartHandshake, LockKeyhole, Moon, Phone, ShieldCheck } from 'lucide-react';

type CheckIn = { energy: number; stress: number; sleep: number; note: string; savedAt: string };
const KEY = 'stagewire-work-life-checkin-v14';
function read(): CheckIn { try { return { energy: 3, stress: 3, sleep: 3, note: '', savedAt: '', ...JSON.parse(localStorage.getItem(KEY) || '{}') }; } catch { return { energy: 3, stress: 3, sleep: 3, note: '', savedAt: '' }; } }
export default function WorkLifePage() {
  const [check, setCheck] = useState(read); const [saved, setSaved] = useState(false);
  const save = () => { const next = { ...check, savedAt: new Date().toISOString() }; localStorage.setItem(KEY, JSON.stringify(next)); setCheck(next); setSaved(true); window.setTimeout(() => setSaved(false), 2500); };
  return <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">Worker first / private</div><h1 style={{ marginTop: 10 }}>Work / Life</h1><p className="subtitle">A quick check-in for the human doing the work. No score, no boss, no judgment.</p></div><span className="badge badge-finished"><LockKeyhole size={15} /> Private</span></div>
    <section className="card card-pad"><div className="eyebrow">60-second check-in</div><h2 style={{ marginTop: 7 }}>How are you running?</h2><p className="subtitle">Use this for yourself. StageWire does not put it in Career Passport.</p><div className="passport-grid" style={{ marginTop: 20 }}><Scale label="Energy" value={check.energy} low="empty" high="strong" onChange={(energy) => setCheck({ ...check, energy })} /><Scale label="Stress" value={check.stress} low="calm" high="maxed" onChange={(stress) => setCheck({ ...check, stress })} /><Scale label="Sleep" value={check.sleep} low="rough" high="rested" onChange={(sleep) => setCheck({ ...check, sleep })} /></div><div className="field" style={{ marginTop: 20 }}><label htmlFor="work-life-note">Anything you want to remember?</label><textarea id="work-life-note" value={check.note} onChange={(e) => setCheck({ ...check, note: e.target.value })} placeholder="Optional. Keep it short or leave it blank." /></div><div className="form-actions"><button className="btn btn-primary" onClick={save}><HeartHandshake size={19} /> Save for me</button>{saved && <span className="badge badge-active">Saved privately</span>}</div></section>
    <div className="passport-grid" style={{ marginTop: 22 }}><section className="card card-pad"><Moon size={24} /><div className="eyebrow" style={{ marginTop: 12 }}>Recovery matters</div><h2 style={{ marginTop: 7 }}>The next call is not worth wrecking yourself.</h2><p className="subtitle">Long days stack up. If you are exhausted, impaired, or too stressed to work safely, treat that as real information—not weakness.</p></section><section className="card card-pad"><ShieldCheck size={24} /><div className="eyebrow" style={{ marginTop: 12 }}>Privacy boundary</div><h2 style={{ marginTop: 7 }}>This is not a performance record.</h2><p className="subtitle">Work/Life check-ins are for the worker. They do not belong in Career Passport, hiring views, or employer-facing records.</p></section></div>
    <section className="card card-pad" style={{ marginTop: 22 }}><div className="eyebrow">Need a human?</div><h2 style={{ marginTop: 7 }}>Reach outside the app.</h2><p className="subtitle">StageWire should never pretend a wellness screen replaces a real person. If you feel in immediate danger, contact emergency services. In the U.S., you can call or text 988 for crisis support.</p><div className="privacy-rule"><Phone size={18} /> StageWire does not diagnose, counsel, or report this check-in to an employer.</div></section>
  </div>;
}
function Scale({ label, value, low, high, onChange }: { label: string; value: number; low: string; high: string; onChange: (value: number) => void }) { return <div className="card card-pad"><strong>{label}</strong><div className="form-actions" style={{ marginTop: 14 }}>{[1,2,3,4,5].map((n) => <button type="button" key={n} className={`btn ${value === n ? 'btn-primary' : 'btn-quiet'}`} onClick={() => onChange(n)} aria-label={`${label} ${n} of 5`}>{n}</button>)}</div><div className="help-text" style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8 }}><span>{low}</span><span>{high}</span></div></div>; }
