import { Archive, BadgeCheck, Camera, CheckCircle2, FileText, LockKeyhole, MapPin, Printer, ReceiptText, ShieldCheck, WalletCards } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { useGetCallWorkday } from '@workspace/api-client-react';
function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value || 0); }
function when(value?: string | null) { if (!value) return 'Not recorded'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date); }
function workDate(value: string) { const date = new Date(`${value}T12:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'long', day: 'numeric', year: 'numeric' }).format(date); }
function Datum({ label, value }: { label: string; value: string }) { return <div><div className="receipt-label">{label}</div><div className="receipt-value">{value}</div></div>; }
const RESERVE_KEY = 'stagewire-tax-reserve-percent-v14';
function reservePercent() { const saved = Number(localStorage.getItem(RESERVE_KEY)); return saved >= 0 && saved <= 100 ? saved : 25; }
export default function WorkReceiptPage() {
  const { id } = useParams<{ id: string }>(); const callId = Number(id); const workday = useGetCallWorkday(callId); const data = workday.data; const call = data?.call;
  if (!Number.isFinite(callId) || callId <= 0) return <div className="page-wrap"><div className="error-box"><strong>Invalid receipt.</strong></div></div>;
  if (workday.isLoading) return <div className="page-wrap"><div className="card card-pad"><h2>Opening work receipt…</h2></div></div>;
  if (workday.isError || !data || !call) return <div className="page-wrap"><div className="error-box"><strong>This receipt could not be loaded.</strong><button className="btn btn-quiet" onClick={() => workday.refetch()}>Try again</button></div></div>;
  const completedChecklist = data.checklist.items.filter((item) => item.checked).length; const expenseTotal = data.expenses.reduce((sum, item) => sum + item.amount, 0); const netBeforeTax = Math.max(0, (call.gross || 0) - expenseTotal); const reserve = reservePercent(); const taxReserve = Math.max(0, netBeforeTax * (reserve / 100)); const afterReserve = Math.max(0, netBeforeTax - taxReserve);
  return <div className="page-wrap"><div className="page-heading print-hide"><div><Link href="/vault-v14" className="link-text">The Vault</Link><div className="eyebrow" style={{ marginTop: 22 }}>Permanent worker record / #{call.id}</div><h1 style={{ marginTop: 10 }}>Call Receipt</h1><p className="subtitle">The call is closed. This one record now feeds your work history, Vault, Career Passport, and money picture.</p></div><button className="btn btn-primary" onClick={() => window.print()}><Printer size={19} /> Print / save PDF</button></div>
    <div className="success-box print-hide"><CheckCircle2 size={22} /><div><strong>Call locked.</strong><span> No retyping the same shift somewhere else.</span></div></div>
    <article className="card card-pad receipt-paper" data-testid={`work-receipt-${call.id}`}><header className="receipt-head"><div><div className="eyebrow">StageWire / Work Receipt</div><h2 style={{ marginTop: 8 }}>{call.showName}</h2><p className="call-meta"><MapPin size={16} /> {call.venue}{call.venueAddress ? ` · ${call.venueAddress}` : ''}</p><p className="call-meta">{workDate(call.workDate)} · {call.role}</p></div><div style={{ textAlign: 'right' }}><div className="receipt-label">Estimated gross</div><div className="receipt-total">{money(call.gross)}</div><span className="badge badge-finished"><CheckCircle2 size={14} /> Finished</span></div></header>
    <div className="receipt-grid"><Datum label="Arrival" value={when(call.arrivalAt)} /><Datum label="Paid start" value={when(call.actualStart)} /><Datum label="Actual end" value={when(call.actualEnd)} /><Datum label="Break" value={`${call.breakMinutes} minutes`} /><Datum label="Hours worked" value={`${call.hours} hours`} /><Datum label="Role performed" value={call.role} /><Datum label="Pay type" value={call.payType} /><Datum label="Rate" value={money(call.hourlyRate)} /><Datum label="Minimum hours" value={`${call.minimumHours} hours`} /><Datum label="Mileage" value={`${call.mileage || 0} mi`} /><Datum label="Parking" value={money(call.parkingExpense)} /><Datum label="Tolls" value={money(call.tollExpense)} /></div>
    <section className="card" style={{ padding: 18, marginTop: 24 }}><div className="eyebrow">One-entry handoff</div><h2 style={{ marginTop: 7 }}>StageWire carries this forward.</h2><div className="stats-grid" style={{ marginTop: 14 }}><div className="card stat-card"><span className="stat-label">The Vault</span><strong className="stat-value"><Archive size={22} /> Saved</strong></div><div className="card stat-card"><span className="stat-label">Career record</span><strong className="stat-value"><BadgeCheck size={22} /> Updated</strong></div><div className="card stat-card"><span className="stat-label">Money record</span><strong className="stat-value"><WalletCards size={22} /> Updated</strong></div></div></section>
    <section className="card" style={{ padding: 18, marginTop: 24 }}><div className="eyebrow">Money snapshot</div><h2 style={{ marginTop: 7 }}>What this call means</h2><p className="help-text">Planning only. This uses your {reserve}% Money reserve setting. It does not move money, calculate your actual tax bill, or file anything.</p><div className="receipt-grid" style={{ marginTop: 16 }}><Datum label="Estimated gross" value={money(call.gross)} /><Datum label="Logged expenses" value={money(expenseTotal)} /><Datum label="After logged expenses" value={money(netBeforeTax)} /><Datum label={`${reserve}% reserve plan`} value={money(taxReserve)} /><Datum label="After reserve plan" value={money(afterReserve)} /></div></section>
    <section className="card" style={{ padding: 18, marginTop: 24 }}><div className="eyebrow">Workday completion</div><div className="stats-grid" style={{ marginTop: 14 }}><div className="card stat-card"><span className="stat-label">Checklist</span><strong className="stat-value">{completedChecklist}/{data.checklist.items.length}</strong></div><div className="card stat-card"><span className="stat-label">Saved notes</span><strong className="stat-value">{data.notes.length}</strong></div><div className="card stat-card"><span className="stat-label">Expenses logged</span><strong className="stat-value">{money(expenseTotal)}</strong></div></div></section>
    {data.expenses.length > 0 && <section style={{ marginTop: 26 }}><div className="eyebrow">Expenses</div><div className="vault-items">{data.expenses.map((expense) => <div className="vault-item" key={expense.id}><span><b>{expense.category}</b>{expense.description ? ` · ${expense.description}` : ''}</span><span>{money(expense.amount)}</span></div>)}</div></section>}
    {data.notes.length > 0 && <section style={{ marginTop: 26 }}><div className="eyebrow">Private work notes</div><div className="vault-items">{data.notes.map((note) => <div className="vault-item" key={note.id}><span>{note.text}</span><span>{note.category || 'note'}</span></div>)}</div></section>}
    {data.checklist.items.length > 0 && <section style={{ marginTop: 26 }}><div className="eyebrow">Call checklist record</div><div className="experience-list">{data.checklist.items.map((item) => <div className="experience-row" key={item.id}><span><b>{item.label}</b><small>{item.isSuggested ? 'role suggestion' : item.isCustom ? 'worker-added' : 'call item'}</small></span><span>{item.checked ? <CheckCircle2 size={20} /> : '—'}</span></div>)}</div></section>}
    {(call.receiptAttachmentName || call.workPhotoName) && <section className="receipt-attachments"><div className="eyebrow">Attachments</div><div className="attachment-list">{call.receiptAttachmentName && <span className="attachment-pill"><FileText size={17} /> {call.receiptAttachmentName}</span>}{call.workPhotoName && <span className="attachment-pill"><Camera size={17} /> {call.workPhotoName}</span>}</div></section>}
    <footer className="receipt-foot"><span><LockKeyhole size={15} /> Private by default</span><span><ShieldCheck size={15} /> Worker-owned record</span><span><ReceiptText size={15} /> StageWire #{call.id}</span></footer></article>
    <div className="card card-pad print-hide" style={{ marginTop: 22 }}><div className="eyebrow">Done with this call</div><h2 style={{ marginTop: 7 }}>Where do you want to go?</h2><div className="form-actions" style={{ marginTop: 16 }}><Link href="/vault-v14" className="btn btn-primary"><Archive size={19} /> Open The Vault</Link><Link href="/passport-v14" className="btn btn-secondary"><BadgeCheck size={19} /> Career Passport</Link><Link href="/calls?new=1" className="btn btn-quiet">Add next call</Link></div></div>
  </div>;
}
